### PR TITLE
started forms/modal layout for commission requests

### PR DESCRIPTION
**Pull request by pandabear189**
**FILL OUT THE FIELDS BELOW!**

**Discord Username and Tag**
Ex: Space#9878

**Describe the Changes You've Created**

**Where are these changes going?**
Specific Sub-Servers or the Main Server

**Confirm that you have done the following:**
- [x] Created a new folder for your bot under utils/bots/~
- [x] Moved any events under the events folder. 
- [x] Properly Documented the code changes
- [x] DM'd Space for a new Documentation Page (for new commands)
- [x] Tested the New Files on your own and you confirm that the changes are bug free.

**Additional Context**
Add any other information about the Pull Request here.

### CODE REVIEW

**Comment by pandabear189** [comment]
do you like the planned like implementation?

**Comment by pandabear189** [comment]
#134

**Review by Space-Turtle0 — CHANGES_REQUESTED** [review]
My bad for not pointing this out earlier, but let’s use threads instead since we can just rely on discord for automatic archiving. 
When creating a thread, set it 24 hours before archiving.

**Comment by pandabear189** [comment]
so like no forms? or we just create a thread and use the existing implementation?

**Comment by Space-Turtle0** [comment]
No we'll still use forms.

The process is going to be like this:

- User clicks a button (similar to the ticket system over on the main server) and the form pops up.
- Upon completion, the bot sends an embed with **only** the title, short description, and pings the requester in that message.
- Then the bot creates an thread based on that message and pings them and the bot developer team.
- And that's it

**Comment by pandabear189** [comment]
huh ok makes sense, i only made the modals today nothing else, next week i will owkr on the other stuff 👍

**Comment by Space-Turtle0** [comment]
dw it's fine, I'll probably take this over since we might change the process as this gets finished. 
Apologies for the confusion. But great work, this'll definitely help with jumpstarting the new process!

**Pull request merged**
